### ISSUE TITLE
Failing the devid and vendor id check

### ISSUE THREAD

**Issue by ayubowan2u** [markusj/upd72020x-load#8] opened 2020-09-01 11:57 UTC
Hi Markus,

When I run the upd72020x_load, the program returns an error ERROR: wrong vendorid/devid. Expected an UPD720201 or UPD720202 chip and this is not one!

My device details are 
03:00.0 USB controller: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller (rev 03)

I note that the code checks for the pcicfgfile and I can confirm that I do have the config file at /sys/bus/pci/devices/0000:03:00.0/ directory and that the device file and vendor files give the devid and vendorid  as expected in your program. However, the code trying to check the device id, pcidevid_x1,  appear to fail and the program terminates. 

Would appreciate your thoughts/comments on this issue. Can I safely bypass this check?

Guptila

**Comment by markusj** [comment] 2020-09-28 21:27
> Would appreciate your thoughts/comments on this issue. Can I safely bypass this check?

I am reluctant to say yes, because if this check fails, something must be horribly wrong. Can you please provide the output of `lspci -nn`, the commandline used for upd72020x_load and the full output?

**Comment by ayubowan2u** [comment] 2020-09-29 11:34
Hi Markus, since posting my query I did more testing and it appears one of the problems was the USB3.0 hub I had connected to the Renesas card. I think the power rating for the hub does not meet the requirements and this may have caused some issues. Once I removed the USB hub, the driver for Renesas card gets loaded correctly. I then tested it by plugging a USB3.0 drive and it now shows as a 5000M drive.

Among the many things I tried out was doing a firmware update using Windows 7 which I have as a dual boot system.

However, I would like to be able to use your script and would like to find out why it is failing.

lspci -nn gives me

00:00.0 Host bridge [0600]: Intel Corporation 2nd Generation Core Processor Family DRAM Controller [8086:0100] (rev 09)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port [8086:0101] (rev 09)
00:16.0 Communication controller [0780]: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 [8086:1c3a] (rev 04)
00:16.3 Serial controller [0700]: Intel Corporation 6 Series/C200 Series Chipset Family KT Controller [8086:1c3d] (rev 04)
00:19.0 Ethernet controller [0200]: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) [8086:1502] (rev 04)
00:1a.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 [8086:1c2d] (rev 04)
00:1b.0 Audio device [0403]: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller [8086:1c20] (rev 04)
00:1c.0 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 [8086:1c10] (rev b4)
00:1c.4 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 [8086:1c18] (rev b4)
00:1c.6 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 [8086:1c1c] (rev b4)
00:1c.7 PCI bridge [0604]: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 8 [8086:1c1e] (rev b4)
00:1d.0 USB controller [0c03]: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 [8086:1c26] (rev 04)
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev a4)
00:1f.0 ISA bridge [0601]: Intel Corporation Q67 Express Chipset LPC Controller [8086:1c4e] (rev 04)
00:1f.2 SATA controller [0106]: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller [8086:1c02] (rev 04)
00:1f.3 SMBus [0c05]: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller [8086:1c22] (rev 04)
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series] [1002:68f9]
01:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series] [1002:aa68]
03:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller [1912:0014] (rev 03)

and the command used for upd72020x_load is

./upd72020x-load -u -b 0x03 -f 0x0 -d 0x00 -i K2026.mem

and the output is

Doing the upload
bus = 3 
dev = 0 
fct = 0 
fname = K2026.mem 
ERROR: wrong vendorid/devid. Expected an UPD720201 or UPD720202 chip and this is not one!
 ======> FAILED

Appreciate your help.

**Comment by markusj** [comment] 2020-09-29 19:07
Hmm, I do not see anything suspicious, but I am still wondering why you were able to read the correct content from /config and the tool not. Maybe some hardware glitch due to the power ratings you mentioned. I will add a line to output the vendor and device IDs when they did not match, so at least we obtain a bit more knowledge when things fail. Maybe you take a look at the most recent lines in dmesg when the problem appears again.

**Comment by markusj** [comment] 2020-11-29 19:17
Closing this until further information is available or the bug can be confirmed/reproduced.

**Closed by markusj** 2020-11-29 19:17 UTC
